[platformio]
default_envs = wifi_s3

[common]
; Override: usa python3 invece di python per git-version.py
build_flags =
    !python3 git-version.py
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ASYNC_TCP_MAX_ACK_TIME=5000
    -DCONFIG_ASYNC_TCP_PRIORITY=10
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=64
    -DWS_MAX_QUEUED_MESSAGES=32
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
    -DCONFIG_ASYNC_TCP_STACK_SIZE=8192
    -DASYNCWEBSERVER_LOG_LEVEL=ASYNC_WS_LOG_NONE
    -DASYNCWEBSERVER_USE_CHUNK_INFLIGHT=1
    -Wno-unused-variable
    -Wno-unused-function

[env:wifi_s3]
; AlgoLaser DKM1 — ESP32-S3R8, 16MB flash
board_build.partitions = FluidNC/ld/esp32s3/app3M_spiffs1M_8MB.csv
upload_port = /dev/cu.usbmodem14101
monitor_port = /dev/cu.usbmodem14101
monitor_speed = 115200
